version: "3.1"

services:
  my-congestion-manager:
    image: congestion-manager
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      RPC_HOST: '127.0.0.1'
      RPC_PORT: 8332
      RPC_USERNAME: 'test'
      RPC_PASSWORD: 'test'
      WAMP_WS: 'ws://localhost:8080/ws'
      WAMP_REALM: 'realm1'
      WAMP_KEY: 'bcm-be'
      WAMP_USER: 'bcm-be'
      WAMP_ROLE: 'bcm-be'
      ZMQ_URL: 'tcp://localhost:28333'
      REDIS_PORT: 6379
      REDIS_HOST: 'localhost'
      REDIS_PREFIX: 'app:'
      CURRENCY: 'btc'
      COIN_NETWORK: 'main'
      RELIABLE_MINED_BLOCK_THRESHOLD: 500
      INIT_BLOCK_SIZE: 1e+6
      AVG_BLOCK_TIME: 10
